window.trees_2 = [{
  "id": 11,
  "label": "System",
  "parent_id": null,
  "depth": 0,
  "child_num": 3,
  "description": "System Manager",
  "children": [{
    "id": 12,
    "label": "base",
    "parent_id": 11,
    "depth": 1,
    "child_num": 5,
    "description": "Base Manager",
    "children": [{
      "id": 13,
      "label": "Menus",
      "parent_id": 12,
      "depth": 2,
      "child_num": 0,
      "description": "menu manager",
    }, {
      "id": 14,
      "label": "Roles",
      "parent_id": 12,
      "depth": 2,
      "child_num": 0,
      "description": "Role Manager",
    }, {
      "id": 15,
      "label": "Users",
      "parent_id": 12,
      "depth": 2,
      "child_num": 0,
      "description": "User Manager",
    }]
  }]
}, {
  "id": 16,
  "label": "Customs",
  "parent_id": null,
  "url": null,
  "depth": 0,
  "child_num": 2,
  "description": "Custom Manager",
  "children": [{
    "id": 17,
    "label": "CustomList",
    "parent_id": 16,
    "depth": 1,
    "child_num": 0,
    "description": "CustomList",
  }]
}, {
  "id": 18,
  "label": "Templates",
  "parent_id": null,
  "url": null,
  "depth": 0,
  "child_num": 1,
  "description": "Template Manager",
  "children": [{
    "id": 19,
    "label": "TemplateList",
    "parent_id": 18,
    "depth": 1,
    "child_num": 0,
    "description": "Template Manager",
  }]
}, {
  "id": 110,
  "label": "Bussiness",
  "parent_id": null,
  "url": null,
  "depth": 0,
  "child_num": 2,
  "description": "Bussiness Manager",
  "children": [{
    "id": 111,
    "label": "BussinessList",
    "parent_id": 110,
    "url": null,
    "depth": 1,
    "child_num": 2,
    "description": "BussinessList",
    "children": [{
      "id": 112,
      "label": "Currencies",
      "parent_id": 111,
      "depth": 2,
      "child_num": 0,
      "description": "Currencies",
    }, {
      "id": 113,
      "label": "Dealtypes",
      "parent_id": 111,
      "depth": 2,
      "child_num": 0,
      "description": "Dealtypes",
    }]
  }, {
    "id": 114,
    "label": "Products",
    "parent_id": 110,
    "url": null,
    "depth": 1,
    "child_num": 2,
    "description": "Products",
    "children": [{
      "id": 115,
      "label": "ProductTypes",
      "parent_id": 114,
      "depth": 2,
      "child_num": 0,
      "description": "ProductTypes",
    }, {
      "id": 116,
      "label": "ProductList",
      "parent_id": 114,
      "depth": 2,
      "child_num": 0,
      "description": "ProductList",
    }]
  }]
}]